# Generated by Django 3.1.1 on 2020-10-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyactivity',
            name='category',
            field=models.CharField(choices=[('Outcome', (('expenses', 'Expenses'), ('upkeep', 'Upkeep'), ('unforeseen', 'Unforeseen'))), ('Income', (('monthly income', 'Monthly Income'), ('other', 'Other')))], default='Outcome', max_length=200),
        ),
        migrations.AddField(
            model_name='moneygoals',
            name='category',
            field=models.CharField(choices=[('Small Goal', 'Small Goal'), ('Liability Goal', 'Liability Goal'), ('Life Goal', 'Life Goal'), ('Investment Goal', 'Investment Goal')], default='Small Goal', max_length=200),
        ),
    ]
