# Generated by Django 3.1.1 on 2020-10-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0003_auto_20201008_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MGMT.moneyuser'),
        ),
        migrations.AddField(
            model_name='moneygoals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MGMT.moneyuser'),
        ),
    ]
