# Generated by Django 3.1.1 on 2020-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0004_auto_20201008_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyactivity',
            name='naming',
            field=models.CharField(blank=True, default='Expenses', max_length=200),
        ),
    ]
