# Generated by Django 3.1.1 on 2020-10-09 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0005_auto_20201008_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneygoals',
            old_name='preffered_date',
            new_name='due_date',
        ),
    ]
