# Generated by Django 3.1.1 on 2020-10-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0007_auto_20201009_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyuser',
            old_name='balance',
            new_name='worth',
        ),
    ]
