# Generated by Django 3.1.1 on 2020-10-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0008_auto_20201010_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyactivity',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='moneygoals',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
