# Generated by Django 3.1.1 on 2020-10-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0009_auto_20201011_1012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='moneyActivity',
            new_name='moneyRecord',
        ),
    ]
