# Generated by Django 3.1.1 on 2020-10-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0012_auto_20201014_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneygoals',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='moneygoals',
            name='naming',
            field=models.CharField(default='Goal', max_length=200),
        ),
        migrations.AlterField(
            model_name='moneyrecord',
            name='naming',
            field=models.CharField(blank=True, default='Record', max_length=200),
        ),
        migrations.AlterField(
            model_name='moneyuser',
            name='email',
            field=models.EmailField(default='mail@mail.mail', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moneyuser',
            name='name',
            field=models.CharField(default='Username', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='moneyuser',
            name='worth',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7),
        ),
    ]
