# Generated by Django 3.1.1 on 2020-10-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0013_auto_20201014_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneygoals',
            name='calculated_date',
        ),
    ]
