# Generated by Django 3.1.1 on 2020-10-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0017_savingsjar_desired_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsjar',
            old_name='Desired_amount',
            new_name='desired_amount',
        ),
    ]
