# Generated by Django 3.1.1 on 2020-10-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0018_auto_20201017_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsjar',
            name='naming',
            field=models.CharField(blank=True, default='Savings-Jar', max_length=200),
        ),
    ]
