# Generated by Django 3.1.1 on 2020-10-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0019_auto_20201017_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyrecord',
            old_name='date_created',
            new_name='date',
        ),
    ]
