# Generated by Django 3.1.1 on 2020-10-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0020_auto_20201017_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
