# Generated by Django 3.1.1 on 2020-10-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0021_auto_20201017_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingsjar',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
