# Generated by Django 3.1.1 on 2020-10-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0022_auto_20201023_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
