# Generated by Django 3.1.1 on 2020-10-24 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0023_auto_20201023_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
