# Generated by Django 3.1.1 on 2020-10-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0025_completedmoneygoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsjar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
