# Generated by Django 3.1.1 on 2020-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0026_auto_20201031_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyuser',
            name='warning_amount',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=7),
        ),
    ]
