# Generated by Django 3.1.1 on 2020-11-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0027_moneyuser_warning_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='growthInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(blank=True, default='Savings-Jar', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('set_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_length', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MGMT.moneyuser')),
            ],
        ),
    ]
