# Generated by Django 3.1.1 on 2020-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MGMT', '0028_growthinvestment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedmoneygoals',
            name='naming',
            field=models.CharField(default='Completed-Goal', max_length=200),
        ),
        migrations.AlterField(
            model_name='growthinvestment',
            name='naming',
            field=models.CharField(blank=True, default='Invest-Plan', max_length=200),
        ),
    ]
